config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login' => 'sessions#new', :as => :login
  get 'signup' => 'members#new', :as => :signup
  delete 'logout' => 'sessions#destroy', :as => :logout

  resources :errors, only: [:show, :index]
  # resources :members, only: [:index]
  resources :users, only: [:index]
  resources :accounts, only: [:show]
  resources :installations, only: [:show, :index]
  resources :settings, only: [:index]

  mount_devise_token_auth_for "Member", at: 'api/v1/auth', controllers: {
    omniauth_callbacks: 'overrides/omniauth_callbacks'
  }
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :errors, only: [:create, :index, :show]
      resources :users, only: [:index]
      resources :members, only: [:show]
      resources :websites, only: [:index]
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  extend Enumerize
  has_many :messages
  has_and_belongs_to_many :subscribers, join_table: "subscriber_issues"
  belongs_to :website
  enumerize :status, in: {:unresolved => 1, :resolved => 2}, default: :unresolved


  validates :description, :presence => true, length: {minimum: 10}
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable
  include DeviseTokenAuth::Concerns::User
  has_many :websites

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  attr_accessor :confirm_success_url
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :issue

  delegate :subscriber, to: :issue

  validates :content, presence: true, length:{ minimum: 10}
  validates :issue, :presence => true


end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  belongs_to :website
  has_and_belongs_to_many :issues, join_table: "subscriber_issues"

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :website, :presence => true
end

app/models/subscriber_issue.rb
class SubscriberIssue < ActiveRecord::Base
  belongs_to :issue
  belongs_to :subscriber

  validates :subscriber, presence: true
  validates :issue, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :website
  has_and_belongs_to_many :issues, join_table: "user_issues"

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :website, :presence => true
end

app/models/website.rb
class Website < ActiveRecord::Base
  belongs_to :member
  has_many :subscribers
  has_many :issues

  validates :title, :presence => true
  validates :domain, :presence => true
  validates :member, :presence => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def index
  end

  def show 
    gon.error_id = params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "landing"
  skip_before_action :authenticate_member!

  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  layout "landing", only: [:new, :create]
  skip_before_action :authenticate_member!

  def new
  end

  def create
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "landing"
  skip_before_action :authenticate_member!

  def new
  end

  def create
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, link_params={}, icon_name=nil)
    class_name = current_page?(link_path) ? 'active' : ''
    html = ""

    content_tag(:li, :class => class_name) do
      link_to link_path, link_params do
        html << icon(icon_name) unless icon_name.nil?
        html << link_text
        html.html_safe
      end
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.haml
#sidebar
  #profile.user-sidebar
    %img.profileimg{:src => "http://0.gravatar.com/avatar/59b762ebf3d116bf806bcfa3fa12e65f"}/
    %p.name Hello, woubuc
    .row.links.hidden-sm.hidden-xs
      .col-xs-6
        %a{:href => ""} Account
      .col-xs-6
        %a.right{:href => "#", :onclick => 'EpicLogger.logout()'} Log out
    %button.btn.btn-primary.fa.fa-bars.visible-sm.visible-xs.pull-right{"data-toggle" => "collapse", :href => "#collapse_menu"}
  #collapse_menu.collapse.in
    .selectbox.closed
      %p.picked-website
        %strong.title Current Site Name
        %span.closed.fa.fa-chevron-down
        %span.open.fa.fa-chevron-up
      #websites-sidebar.options
        %p.title{onclick: 'EpicLogger.pickWebsite(this)', 'data-id'=> ""} Another site
    %ul.nav.nav-pills.nav-stacked
      = nav_link "Errors", errors_url(), {}, 'exclamation-triangle'
      = nav_link "Users", users_url(), {}, 'users'
    %ul.nav.nav-pills.nav-stacked
      = nav_link "Installation", installations_url(), {}, 'code'
      = nav_link "Website Settings", settings_url(), {}, 'cog'
    %ul.nav.nav-pills.nav-stacked.hidden-md.hidden-lg
      %li#menu_account
        %a{:href => "#"}
          %span.fa.fa-user
          Account
      %li#menu_signout
        %a{:href => "#"}
          %span.fa.fa-sign-out
          Log out
    %ul.nav.nav-pills.nav-stacked
      = nav_link "Help", 'mailto:info@epiclogger.com', {'data-helpful'=>'epiclogger','data-helpful-modal'=>"on", :class=>'helpful-link'}, 'question'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Epiclogger

    %meta{:charset => "utf-8"}/
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "Engage developers with users to solve errors", :name => "description"}/

    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-eval' => false
    %script{:async => "", :src => "https://assets.helpful.io/assets/widget.js"}

    = csrf_meta_tags
  %body{:id=>"#{controller.controller_name}-#{controller.action_name}"}
    .loading.j-cloak
    = render partial: 'layouts/menu'
    #maincontainer.container-fluid
      = yield
    - if Rails.application.assets.find_asset("pages/#{controller.controller_name}")
      = javascript_include_tag "pages/#{controller.controller_name}"

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %title Epiclogger

    %meta{:charset => "utf-8"}/
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "Engage developers with users to solve errors", :name => "description"}/

    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{:id=>"#{controller.controller_name}-#{controller.action_name}"}
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-eval' => false
    - if Rails.application.assets.find_asset("pages/#{controller.controller_name}")
      = javascript_include_tag "pages/#{controller.controller_name}"